from __future__ import annotations

from datetime import datetime, timezone

from app.extensions import db
from app.core.enums.reports_enums import ReportFormat, ReportType


def _utcnow() -> datetime:
    """Return the current UTC datetime."""
    return datetime.now(timezone.utc)


class GeneratedReport(db.Model):
    """
    Metadata record for a generated report.

    Report contents are generated by the reports service from the
    application's current data. This model stores report metadata,
    ownership/scope, generation context, filters, and the resulting
    file location.

    clinic_id is nullable because the reports service may support
    system-wide reports for authorized administrative users.

    generated_by_id is nullable because a system-level report may
    optionally exist without an associated staff member.
    """

    __tablename__ = "generated_reports"

    id = db.Column(
        db.Integer,
        primary_key=True,
    )

    # ------------------------------------------------------------------
    # Report scope / ownership
    # ------------------------------------------------------------------

    clinic_id = db.Column(
        db.Integer,
        db.ForeignKey("clinics.id"),
        nullable=True,
        index=True,
    )

    generated_by_id = db.Column(
        db.Integer,
        db.ForeignKey("staff.id"),
        nullable=True,
        index=True,
    )

    # ------------------------------------------------------------------
    # Report definition
    # ------------------------------------------------------------------

    report_type = db.Column(
        db.Enum(ReportType),
        nullable=False,
        index=True,
    )

    report_format = db.Column(
        db.Enum(ReportFormat),
        nullable=False,
        default=ReportFormat.PDF,
        index=True,
    )

    # ------------------------------------------------------------------
    # Report configuration / output
    # ------------------------------------------------------------------

    filters = db.Column(
        db.JSON,
        nullable=True,
    )

    file_url = db.Column(
        db.String(255),
        nullable=True,
    )

    # ------------------------------------------------------------------
    # Timestamps
    # ------------------------------------------------------------------

    created_at = db.Column(
        db.DateTime,
        default=_utcnow,
        nullable=False,
        index=True,
    )

    updated_at = db.Column(
        db.DateTime,
        default=_utcnow,
        onupdate=_utcnow,
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    clinic = db.relationship(
        "Clinic",
        back_populates="generated_reports",
    )

    generated_by = db.relationship(
        "Staff",
        back_populates="generated_reports",
    )

    # ------------------------------------------------------------------
    # Representation
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        return (
            f"<GeneratedReport "
            f"id={self.id} "
            f"report_type={self.report_type.value!r} "
            f"report_format={self.report_format.value!r} "
            f"clinic_id={self.clinic_id} "
            f"generated_by_id={self.generated_by_id} "
            f"created_at={self.created_at!r}>"
        )