"""lab model fixed

Revision ID: 05030326d223
Revises: 791b6e602bbe
Create Date: 2026-09-03 08:36:50.248692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05030326d223'
down_revision = '791b6e602bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=255), nullable=True))

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('critical_low', sa.Numeric(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('critical_high', sa.Numeric(precision=10, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_column('critical_high')
        batch_op.drop_column('critical_low')

    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
