"""initial migrate

Revision ID: 0fa876c74ec9
Revises: 2dadf8187f40
Create Date: 2026-09-04 11:07:22.996855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa876c74ec9'
down_revision = '2dadf8187f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icd10_code', sa.String(length=10), nullable=True))

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rxnorm_code', sa.String(length=20), nullable=True))

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loinc_code', sa.String(length=20), nullable=True))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emirates_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('umrn', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['umrn'])
        batch_op.create_unique_constraint(None, ['emirates_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('umrn')
        batch_op.drop_column('emirates_id')

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_column('loinc_code')

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_column('rxnorm_code')

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_column('icd10_code')

    # ### end Alembic commands ###
