"""notification provider and asset control updates

Revision ID: 1854106c66a4
Revises: dfc4ce4e901a
Create Date: 2026-09-11 13:52:20.021138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1854106c66a4'
down_revision = 'dfc4ce4e901a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('MEDICAL_EQUIPMENT', 'MEDICAL_DEVICE', 'IT_EQUIPMENT', 'COMPUTER', 'NETWORK_EQUIPMENT', 'FURNITURE', 'VEHICLE', 'OPERATIONAL_EQUIPMENT', 'FACILITY_EQUIPMENT', 'OTHER', name='asset_category'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ASSIGNED', 'IN_STORAGE', 'UNDER_MAINTENANCE', 'OUT_OF_SERVICE', 'LOST', 'RETIRED', 'DISPOSED', name='asset_status'), nullable=False),
    sa.Column('condition', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'POOR', 'DAMAGED', 'NON_FUNCTIONAL', name='asset_condition'), nullable=False),
    sa.Column('ownership', sa.Enum('CLINIC', 'LEASED', 'RENTED', 'GOVERNMENT', 'DONATED', 'OTHER', name='asset_ownership'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('model_number', sa.String(length=150), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('maintenance_status', sa.Enum('NOT_REQUIRED', 'SCHEDULED', 'DUE', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', name='maintenance_status'), nullable=False),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('retirement_date', sa.Date(), nullable=True),
    sa.Column('disposal_date', sa.Date(), nullable=True),
    sa.Column('disposal_reason', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('disposal_date IS NULL OR retirement_date IS NULL OR disposal_date >= retirement_date', name='ck_assets_disposal_after_retirement'),
    sa.CheckConstraint('purchase_cost IS NULL OR purchase_cost >= 0', name='ck_assets_purchase_cost_non_negative'),
    sa.CheckConstraint('retirement_date IS NULL OR purchase_date IS NULL OR retirement_date >= purchase_date', name='ck_assets_retirement_after_purchase'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_category'), ['category'], unique=False)
        batch_op.create_index('ix_assets_clinic_asset_tag', ['clinic_id', 'asset_tag'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_condition'), ['condition'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_maintenance_status'), ['maintenance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_next_maintenance_date'), ['next_maintenance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_ownership'), ['ownership'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.drop_index(batch_op.f('ix_assets_serial_number'))
        batch_op.drop_index(batch_op.f('ix_assets_ownership'))
        batch_op.drop_index(batch_op.f('ix_assets_next_maintenance_date'))
        batch_op.drop_index(batch_op.f('ix_assets_maintenance_status'))
        batch_op.drop_index(batch_op.f('ix_assets_location'))
        batch_op.drop_index(batch_op.f('ix_assets_is_active'))
        batch_op.drop_index(batch_op.f('ix_assets_condition'))
        batch_op.drop_index(batch_op.f('ix_assets_clinic_id'))
        batch_op.drop_index('ix_assets_clinic_asset_tag')
        batch_op.drop_index(batch_op.f('ix_assets_category'))
        batch_op.drop_index(batch_op.f('ix_assets_assigned_to_id'))

    op.drop_table('assets')
    # ### end Alembic commands ###
