"""connections

Revision ID: 1e846644bab0
Revises: b12c036e6ffa
Create Date: 2026-09-04 16:19:02.355549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e846644bab0'
down_revision = 'b12c036e6ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('admitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_admissions_admitted_by_id'), ['admitted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_bed_id'), ['bed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_status'), ['status'], unique=False)

    with op.batch_alter_table('ambulance_trips', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('requested_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_ambulance_trips_admission_id'), ['admission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulance_trips_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulance_trips_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulance_trips_invoice_id'), ['invoice_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ambulance_trips_paramedic_id'), ['paramedic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulance_trips_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulance_trips_vehicle_id'), ['vehicle_id'], unique=False)

    with op.batch_alter_table('ambulance_vehicles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_ambulance_vehicles_clinic_id'), ['clinic_id'], unique=False)

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_beds_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_beds_ward_id'), ['ward_id'], unique=False)
        batch_op.create_unique_constraint('uq_beds_ward_bed_number', ['ward_id', 'bed_number'])

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.alter_column('is_headquarters',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_clinics_parent_clinic_id'), ['parent_clinic_id'], unique=False)

    with op.batch_alter_table('ward_transfers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('transferred_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_ward_transfers_admission_id'), ['admission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ward_transfers_from_bed_id'), ['from_bed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ward_transfers_to_bed_id'), ['to_bed_id'], unique=False)

    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_wards_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wards_ward_type'), ['ward_type'], unique=False)
        batch_op.create_unique_constraint('uq_wards_clinic_name', ['clinic_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.drop_constraint('uq_wards_clinic_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_wards_ward_type'))
        batch_op.drop_index(batch_op.f('ix_wards_clinic_id'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('ward_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ward_transfers_to_bed_id'))
        batch_op.drop_index(batch_op.f('ix_ward_transfers_from_bed_id'))
        batch_op.drop_index(batch_op.f('ix_ward_transfers_admission_id'))
        batch_op.alter_column('transferred_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_parent_clinic_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('is_headquarters',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.drop_constraint('uq_beds_ward_bed_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_beds_ward_id'))
        batch_op.drop_index(batch_op.f('ix_beds_status'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('ambulance_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambulance_vehicles_clinic_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('ambulance_trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambulance_trips_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_ambulance_trips_patient_id'))
        batch_op.drop_index(batch_op.f('ix_ambulance_trips_paramedic_id'))
        batch_op.drop_index(batch_op.f('ix_ambulance_trips_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_ambulance_trips_driver_id'))
        batch_op.drop_index(batch_op.f('ix_ambulance_trips_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_ambulance_trips_admission_id'))
        batch_op.alter_column('requested_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admissions_status'))
        batch_op.drop_index(batch_op.f('ix_admissions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_admissions_bed_id'))
        batch_op.drop_index(batch_op.f('ix_admissions_admitted_by_id'))
        batch_op.alter_column('admitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
