"""ambulance and other relationship connected

Revision ID: 26c78d1f0921
Revises: 415fe9dceaab
Create Date: 2026-09-03 10:07:47.007988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c78d1f0921'
down_revision = '415fe9dceaab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulance_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=30), nullable=False),
    sa.Column('equipment_level', sa.Enum('BLS', 'ALS', 'CCT', name='equipmentlevel'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'MAINTENANCE', 'OUT_OF_SERVICE', name='vehiclestatus'), nullable=False),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('ambulance_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('paramedic_id', sa.Integer(), nullable=True),
    sa.Column('trip_type', sa.Enum('EMERGENCY_PICKUP', 'INTER_FACILITY_TRANSFER', 'DISCHARGE_TRANSPORT', 'NON_EMERGENCY', name='triptype'), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'DISPATCHED', 'EN_ROUTE_TO_PICKUP', 'AT_PICKUP', 'EN_ROUTE_TO_DESTINATION', 'COMPLETED', 'CANCELLED', name='tripstatus'), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.Column('pickup_address', sa.String(length=255), nullable=True),
    sa.Column('pickup_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('pickup_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('destination_address', sa.String(length=255), nullable=True),
    sa.Column('destination_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('destination_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('pickup_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['paramedic_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['ambulance_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ambulance_trips')
    op.drop_table('ambulance_vehicles')
    # ### end Alembic commands ###
