"""fixed relationships and fireign keys

Revision ID: 415fe9dceaab
Revises: 3c759eb0d381
Create Date: 2026-09-03 09:07:58.848675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415fe9dceaab'
down_revision = '3c759eb0d381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
