"""updates and new file

Revision ID: 5284601c0e15
Revises: 88269ea82601
Create Date: 2026-09-06 17:15:01.366532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5284601c0e15'
down_revision = '88269ea82601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation_templates', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_consultation_templates_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultation_templates_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_consultations_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index('ix_consultations_clinic_patient', ['clinic_id', 'patient_id'], unique=False)
        batch_op.create_index('ix_consultations_clinic_staff', ['clinic_id', 'staff_id'], unique=False)
        batch_op.create_index('ix_consultations_clinic_started_at', ['clinic_id', 'started_at'], unique=False)
        batch_op.create_index('ix_consultations_clinic_status', ['clinic_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_consultation_type'), ['consultation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_template_id'), ['template_id'], unique=False)

    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collected_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lab_orders_collected_by_id'), ['collected_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_processed_by_id'), ['processed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_verified_by_id'), ['verified_by_id'], unique=False)
        batch_op.create_foreign_key(None, 'staff', ['collected_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'staff', ['verified_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'staff', ['processed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lab_orders_verified_by_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_processed_by_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_collected_by_id'))
        batch_op.drop_column('verified_at')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('verified_by_id')
        batch_op.drop_column('processed_by_id')
        batch_op.drop_column('collected_by_id')

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultations_template_id'))
        batch_op.drop_index(batch_op.f('ix_consultations_status'))
        batch_op.drop_index(batch_op.f('ix_consultations_staff_id'))
        batch_op.drop_index(batch_op.f('ix_consultations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_consultations_consultation_type'))
        batch_op.drop_index('ix_consultations_clinic_status')
        batch_op.drop_index('ix_consultations_clinic_started_at')
        batch_op.drop_index('ix_consultations_clinic_staff')
        batch_op.drop_index('ix_consultations_clinic_patient')
        batch_op.drop_index(batch_op.f('ix_consultations_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_consultations_appointment_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('consultation_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_templates_is_active'))
        batch_op.drop_index(batch_op.f('ix_consultation_templates_clinic_id'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
