"""staff completed

Revision ID: 88269ea82601
Revises: c9552919543e
Create Date: 2026-09-06 15:55:24.597191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88269ea82601'
down_revision = 'c9552919543e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('leave_request_id', sa.Integer(), nullable=True),
    sa.Column('excuse_type', sa.Enum('MEDICAL', 'FAMILY', 'EMERGENCY', 'PERSONAL', 'OTHER', name='excusetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='excusestatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('excuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excuses_excuse_type'), ['excuse_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_excuses_leave_request_id'), ['leave_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_excuses_reviewed_by_user_id'), ['reviewed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_excuses_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_excuses_status'), ['status'], unique=False)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_leave_requests_reviewed_by_id'))
        batch_op.create_index(batch_op.f('ix_leave_requests_reviewed_by_user_id'), ['reviewed_by_user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('leave_requests_reviewed_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['reviewed_by_user_id'], ['id'])
        batch_op.drop_column('reviewed_by_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('leave_requests_reviewed_by_id_fkey'), 'staff', ['reviewed_by_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_leave_requests_reviewed_by_user_id'))
        batch_op.create_index(batch_op.f('ix_leave_requests_reviewed_by_id'), ['reviewed_by_id'], unique=False)
        batch_op.drop_column('reviewed_by_user_id')

    with op.batch_alter_table('excuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excuses_status'))
        batch_op.drop_index(batch_op.f('ix_excuses_staff_id'))
        batch_op.drop_index(batch_op.f('ix_excuses_reviewed_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_excuses_leave_request_id'))
        batch_op.drop_index(batch_op.f('ix_excuses_excuse_type'))

    op.drop_table('excuses')
    # ### end Alembic commands ###
