"""Add chat messaging models

Revision ID: 9ee239523799
Revises: 3136bdf41623
Create Date: 2026-09-13 13:40:45.968828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee239523799'
down_revision = '3136bdf41623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('conversation_type', sa.Enum('direct', 'group', 'patient', 'department', 'team', name='chat_conversation_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', 'closed', name='chat_conversation_status_enum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('description IS NULL OR length(trim(description)) > 0', name='ck_chat_conversations_description_nonempty'),
    sa.CheckConstraint('title IS NULL OR length(trim(title)) > 0', name='ck_chat_conversations_title_nonempty'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversations_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index('ix_chat_conversations_clinic_last_message', ['clinic_id', 'last_message_at', 'id'], unique=False)
        batch_op.create_index('ix_chat_conversations_clinic_patient', ['clinic_id', 'patient_id', 'updated_at', 'id'], unique=False)
        batch_op.create_index('ix_chat_conversations_clinic_status_updated', ['clinic_id', 'status', 'updated_at', 'id'], unique=False)
        batch_op.create_index('ix_chat_conversations_clinic_type_status', ['clinic_id', 'conversation_type', 'status', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_consultation_id'), ['consultation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_conversation_type'), ['conversation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_chat_conversations_created_by', ['created_by_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_updated_at'), ['updated_at'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'edited', 'deleted', name='chat_message_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('normal', 'urgent', 'stat', name='chat_message_priority_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_clinic_created_id', ['clinic_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index('ix_chat_messages_conversation_created_id', ['conversation_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_status'), ['status'], unique=False)

    op.create_table('chat_conversation_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('member', 'admin', name='chat_participant_role_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'left', 'removed', name='chat_participant_status_enum'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_chat_conversation_participants_conversation_user')
    )
    with op.batch_alter_table('chat_conversation_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversation_participants_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversation_participants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversation_participants_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversation_participants_last_read_message_id'), ['last_read_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversation_participants_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversation_participants_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversation_participants_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversation_participants_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_chat_participants_clinic_user', ['clinic_id', 'user_id', 'status', 'id'], unique=False)
        batch_op.create_index('ix_chat_participants_conversation_status', ['conversation_id', 'status', 'id'], unique=False)
        batch_op.create_index('ix_chat_participants_user_status', ['user_id', 'status', 'id'], unique=False)

    op.create_table('chat_message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('attachment_type', sa.Enum('file', 'image', 'video', 'audio', 'document', name='chat_attachment_type_enum'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('file_name IS NULL OR length(trim(file_name)) > 0', name='ck_chat_message_attachments_file_name_nonempty'),
    sa.CheckConstraint('file_size_bytes IS NULL OR file_size_bytes >= 0', name='ck_chat_message_attachments_file_size_non_negative'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'storage_key', name='uq_chat_message_attachments_message_storage')
    )
    with op.batch_alter_table('chat_message_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_attachments_attachment_type'), ['attachment_type'], unique=False)
        batch_op.create_index('ix_chat_message_attachments_clinic_created', ['clinic_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_attachments_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_attachments_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_chat_message_attachments_message_created', ['message_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_attachments_message_id'), ['message_id'], unique=False)

    op.create_table('chat_message_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('mention_type', sa.Enum('user', 'staff', 'patient', 'group', name='chat_mention_type_enum'), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=True),
    sa.Column('mentioned_patient_id', sa.Integer(), nullable=True),
    sa.Column('mentioned_conversation_id', sa.Integer(), nullable=True),
    sa.Column('position_start', sa.Integer(), nullable=True),
    sa.Column('position_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                mention_type IN ('user', 'staff')\n                AND mentioned_user_id IS NOT NULL\n                AND mentioned_patient_id IS NULL\n                AND mentioned_conversation_id IS NULL\n            )\n            OR\n            (\n                mention_type = 'patient'\n                AND mentioned_user_id IS NULL\n                AND mentioned_patient_id IS NOT NULL\n                AND mentioned_conversation_id IS NULL\n            )\n            OR\n            (\n                mention_type = 'group'\n                AND mentioned_user_id IS NULL\n                AND mentioned_patient_id IS NULL\n                AND mentioned_conversation_id IS NOT NULL\n            )\n            ", name='ck_chat_message_mentions_target'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['mentioned_conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['mentioned_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'mention_type', 'mentioned_user_id', 'mentioned_patient_id', 'mentioned_conversation_id', name='uq_chat_message_mentions_target')
    )
    with op.batch_alter_table('chat_message_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_mentions_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index('ix_chat_message_mentions_conversation', ['mentioned_conversation_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_mentions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_mentions_mention_type'), ['mention_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_mentions_mentioned_conversation_id'), ['mentioned_conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_mentions_mentioned_patient_id'), ['mentioned_patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_mentions_mentioned_user_id'), ['mentioned_user_id'], unique=False)
        batch_op.create_index('ix_chat_message_mentions_message', ['message_id', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_mentions_message_id'), ['message_id'], unique=False)
        batch_op.create_index('ix_chat_message_mentions_patient', ['mentioned_patient_id', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_chat_message_mentions_user', ['mentioned_user_id', 'created_at', 'id'], unique=False)

    op.create_table('chat_message_pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('pinned_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pinned', 'unpinned', name='chat_pin_status_enum'), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unpinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pinned_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message_pins', schema=None) as batch_op:
        batch_op.create_index('ix_chat_message_pins_clinic_created', ['clinic_id', 'pinned_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_pins_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_pins_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_pins_message_id'), ['message_id'], unique=False)
        batch_op.create_index('ix_chat_message_pins_message_status', ['message_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_pins_pinned_at'), ['pinned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_pins_pinned_by_id'), ['pinned_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_pins_status'), ['status'], unique=False)
        batch_op.create_index('ix_chat_message_pins_status_expires', ['status', 'expires_at', 'id'], unique=False)

    op.create_table('chat_message_read_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('delivered', 'read', name='chat_read_receipt_status_enum'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_chat_message_read_receipts_message_user')
    )
    with op.batch_alter_table('chat_message_read_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_chat_message_read_receipts_clinic_created', ['clinic_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_read_receipts_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_read_receipts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_read_receipts_message_id'), ['message_id'], unique=False)
        batch_op.create_index('ix_chat_message_read_receipts_message_status', ['message_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_read_receipts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_read_receipts_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_chat_message_read_receipts_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message_read_receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_message_read_receipts_user_status')
        batch_op.drop_index(batch_op.f('ix_chat_message_read_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_read_receipts_status'))
        batch_op.drop_index('ix_chat_message_read_receipts_message_status')
        batch_op.drop_index(batch_op.f('ix_chat_message_read_receipts_message_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_read_receipts_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_message_read_receipts_clinic_id'))
        batch_op.drop_index('ix_chat_message_read_receipts_clinic_created')

    op.drop_table('chat_message_read_receipts')
    with op.batch_alter_table('chat_message_pins', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_message_pins_status_expires')
        batch_op.drop_index(batch_op.f('ix_chat_message_pins_status'))
        batch_op.drop_index(batch_op.f('ix_chat_message_pins_pinned_by_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_pins_pinned_at'))
        batch_op.drop_index('ix_chat_message_pins_message_status')
        batch_op.drop_index(batch_op.f('ix_chat_message_pins_message_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_pins_expires_at'))
        batch_op.drop_index(batch_op.f('ix_chat_message_pins_clinic_id'))
        batch_op.drop_index('ix_chat_message_pins_clinic_created')

    op.drop_table('chat_message_pins')
    with op.batch_alter_table('chat_message_mentions', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_message_mentions_user')
        batch_op.drop_index('ix_chat_message_mentions_patient')
        batch_op.drop_index(batch_op.f('ix_chat_message_mentions_message_id'))
        batch_op.drop_index('ix_chat_message_mentions_message')
        batch_op.drop_index(batch_op.f('ix_chat_message_mentions_mentioned_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_mentions_mentioned_patient_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_mentions_mentioned_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_mentions_mention_type'))
        batch_op.drop_index(batch_op.f('ix_chat_message_mentions_created_at'))
        batch_op.drop_index('ix_chat_message_mentions_conversation')
        batch_op.drop_index(batch_op.f('ix_chat_message_mentions_clinic_id'))

    op.drop_table('chat_message_mentions')
    with op.batch_alter_table('chat_message_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_attachments_message_id'))
        batch_op.drop_index('ix_chat_message_attachments_message_created')
        batch_op.drop_index(batch_op.f('ix_chat_message_attachments_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_message_attachments_clinic_id'))
        batch_op.drop_index('ix_chat_message_attachments_clinic_created')
        batch_op.drop_index(batch_op.f('ix_chat_message_attachments_attachment_type'))

    op.drop_table('chat_message_attachments')
    with op.batch_alter_table('chat_conversation_participants', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_participants_user_status')
        batch_op.drop_index('ix_chat_participants_conversation_status')
        batch_op.drop_index('ix_chat_participants_clinic_user')
        batch_op.drop_index(batch_op.f('ix_chat_conversation_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_conversation_participants_updated_at'))
        batch_op.drop_index(batch_op.f('ix_chat_conversation_participants_status'))
        batch_op.drop_index(batch_op.f('ix_chat_conversation_participants_role'))
        batch_op.drop_index(batch_op.f('ix_chat_conversation_participants_last_read_message_id'))
        batch_op.drop_index(batch_op.f('ix_chat_conversation_participants_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_conversation_participants_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_chat_conversation_participants_clinic_id'))

    op.drop_table('chat_conversation_participants')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_status'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_priority'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))
        batch_op.drop_index('ix_chat_messages_conversation_created_id')
        batch_op.drop_index(batch_op.f('ix_chat_messages_clinic_id'))
        batch_op.drop_index('ix_chat_messages_clinic_created_id')

    op.drop_table('chat_messages')
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_conversations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_chat_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_chat_conversations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_chat_conversations_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_chat_conversations_created_by_id'))
        batch_op.drop_index('ix_chat_conversations_created_by')
        batch_op.drop_index(batch_op.f('ix_chat_conversations_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_conversations_conversation_type'))
        batch_op.drop_index(batch_op.f('ix_chat_conversations_consultation_id'))
        batch_op.drop_index('ix_chat_conversations_clinic_type_status')
        batch_op.drop_index('ix_chat_conversations_clinic_status_updated')
        batch_op.drop_index('ix_chat_conversations_clinic_patient')
        batch_op.drop_index('ix_chat_conversations_clinic_last_message')
        batch_op.drop_index(batch_op.f('ix_chat_conversations_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_chat_conversations_appointment_id'))

    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
