"""rewritten  codebases

Revision ID: b12c036e6ffa
Revises: 0fa876c74ec9
Create Date: 2026-09-04 12:41:44.997722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b12c036e6ffa'
down_revision = '0fa876c74ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.alter_column(
            'quantity',
            existing_type=sa.INTEGER(),
            nullable=False
        )
        batch_op.create_index(
            batch_op.f('ix_invoice_items_invoice_id'),
            ['invoice_id'],
            unique=False
        )

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column(
            'is_insurance_claim',
            existing_type=sa.BOOLEAN(),
            nullable=False
        )
        batch_op.alter_column(
            'created_at',
            existing_type=postgresql.TIMESTAMP(),
            nullable=False
        )
        batch_op.alter_column(
            'updated_at',
            existing_type=postgresql.TIMESTAMP(),
            nullable=False
        )
        batch_op.drop_constraint(
            batch_op.f('invoices_invoice_number_key'),
            type_='unique'
        )
        batch_op.create_index(
            batch_op.f('ix_invoices_appointment_id'),
            ['appointment_id'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_invoices_clinic_id'),
            ['clinic_id'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_invoices_invoice_number'),
            ['invoice_number'],
            unique=True
        )
        batch_op.create_index(
            batch_op.f('ix_invoices_patient_id'),
            ['patient_id'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_invoices_status'),
            ['status'],
            unique=False
        )

    # Create the PostgreSQL enum type before adding
    # the payments.gateway column that uses it.
    payment_gateway_enum = postgresql.ENUM(
        'STRIPE',
        'PAYSTACK',
        'FLUTTERWAVE',
        name='paymentgateway',
    )

    payment_gateway_enum.create(
        op.get_bind(),
        checkfirst=True
    )

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'gateway',
                sa.Enum(
                    'STRIPE',
                    'PAYSTACK',
                    'FLUTTERWAVE',
                    name='paymentgateway'
                ),
                nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                'gateway_transaction_id',
                sa.String(length=255),
                nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                'failure_reason',
                sa.String(length=255),
                nullable=True
            )
        )
        batch_op.alter_column(
            'created_at',
            existing_type=postgresql.TIMESTAMP(),
            nullable=False
        )
        batch_op.alter_column(
            'updated_at',
            existing_type=postgresql.TIMESTAMP(),
            nullable=False
        )
        batch_op.create_index(
            batch_op.f('ix_payments_gateway'),
            ['gateway'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_payments_gateway_transaction_id'),
            ['gateway_transaction_id'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_payments_invoice_id'),
            ['invoice_id'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_payments_method'),
            ['method'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_payments_reference'),
            ['reference'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_payments_status'),
            ['status'],
            unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f('ix_payments_status')
        )
        batch_op.drop_index(
            batch_op.f('ix_payments_reference')
        )
        batch_op.drop_index(
            batch_op.f('ix_payments_method')
        )
        batch_op.drop_index(
            batch_op.f('ix_payments_invoice_id')
        )
        batch_op.drop_index(
            batch_op.f('ix_payments_gateway_transaction_id')
        )
        batch_op.drop_index(
            batch_op.f('ix_payments_gateway')
        )
        batch_op.alter_column(
            'updated_at',
            existing_type=postgresql.TIMESTAMP(),
            nullable=True
        )
        batch_op.alter_column(
            'created_at',
            existing_type=postgresql.TIMESTAMP(),
            nullable=True
        )
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('gateway_transaction_id')
        batch_op.drop_column('gateway')

    # Drop the PostgreSQL enum after the column using it
    # has been removed.
    payment_gateway_enum = postgresql.ENUM(
        'STRIPE',
        'PAYSTACK',
        'FLUTTERWAVE',
        name='paymentgateway',
    )

    payment_gateway_enum.drop(
        op.get_bind(),
        checkfirst=True
    )

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f('ix_invoices_status')
        )
        batch_op.drop_index(
            batch_op.f('ix_invoices_patient_id')
        )
        batch_op.drop_index(
            batch_op.f('ix_invoices_invoice_number')
        )
        batch_op.drop_index(
            batch_op.f('ix_invoices_clinic_id')
        )
        batch_op.drop_index(
            batch_op.f('ix_invoices_appointment_id')
        )
        batch_op.create_unique_constraint(
            batch_op.f('invoices_invoice_number_key'),
            ['invoice_number'],
            postgresql_nulls_not_distinct=False
        )
        batch_op.alter_column(
            'updated_at',
            existing_type=postgresql.TIMESTAMP(),
            nullable=True
        )
        batch_op.alter_column(
            'created_at',
            existing_type=postgresql.TIMESTAMP(),
            nullable=True
        )
        batch_op.alter_column(
            'is_insurance_claim',
            existing_type=sa.BOOLEAN(),
            nullable=True
        )

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f('ix_invoice_items_invoice_id')
        )
        batch_op.alter_column(
            'quantity',
            existing_type=sa.INTEGER(),
            nullable=True
        )

    # ### end Alembic commands ###