"""create emergency access

Revision ID: b3a237f3f8b7
Revises: 3f8c2e7a1b44
Create Date: 2026-09-25 10:34:49.423035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a237f3f8b7'
down_revision = '3f8c2e7a1b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_access_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('requester_role', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ACTIVE', 'DENIED', 'REVOKED', 'EXPIRED', name='emergencyaccessstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_access_grants', schema=None) as batch_op:
        batch_op.create_index('ix_emergency_access_clinic_patient_status', ['clinic_id', 'patient_id', 'status'], unique=False)
        batch_op.create_index('ix_emergency_access_expires_at', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_access_grants_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_access_grants_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_access_grants_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_access_grants_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_access_grants_requester_user_id'), ['requester_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_access_grants_reviewed_by_user_id'), ['reviewed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_access_grants_status'), ['status'], unique=False)
        batch_op.create_index('ix_emergency_access_requester_status', ['requester_user_id', 'status'], unique=False)

    op.create_table('consent_guard_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergency_access_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_role', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.Enum('ALLOW', 'DENY', 'EMERGENCY_EXCEPTION', name='consentguarddecision'), nullable=False),
    sa.Column('consent_reference', sa.String(length=255), nullable=True),
    sa.Column('policy_context', sa.JSON(), nullable=True),
    sa.Column('emergency_exception', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['emergency_access_id'], ['emergency_access_grants.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_guard_evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_consent_guard_clinic_patient', ['clinic_id', 'patient_id'], unique=False)
        batch_op.create_index('ix_consent_guard_emergency_access', ['emergency_access_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_guard_evaluations_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_guard_evaluations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_guard_evaluations_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_guard_evaluations_emergency_access_id'), ['emergency_access_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_guard_evaluations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_guard_evaluations_requester_user_id'), ['requester_user_id'], unique=False)
        batch_op.create_index('ix_consent_guard_requester_created', ['requester_user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_guard_evaluations', schema=None) as batch_op:
        batch_op.drop_index('ix_consent_guard_requester_created')
        batch_op.drop_index(batch_op.f('ix_consent_guard_evaluations_requester_user_id'))
        batch_op.drop_index(batch_op.f('ix_consent_guard_evaluations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_consent_guard_evaluations_emergency_access_id'))
        batch_op.drop_index(batch_op.f('ix_consent_guard_evaluations_decision'))
        batch_op.drop_index(batch_op.f('ix_consent_guard_evaluations_created_at'))
        batch_op.drop_index(batch_op.f('ix_consent_guard_evaluations_clinic_id'))
        batch_op.drop_index('ix_consent_guard_emergency_access')
        batch_op.drop_index('ix_consent_guard_clinic_patient')

    op.drop_table('consent_guard_evaluations')
    with op.batch_alter_table('emergency_access_grants', schema=None) as batch_op:
        batch_op.drop_index('ix_emergency_access_requester_status')
        batch_op.drop_index(batch_op.f('ix_emergency_access_grants_status'))
        batch_op.drop_index(batch_op.f('ix_emergency_access_grants_reviewed_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_access_grants_requester_user_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_access_grants_requested_at'))
        batch_op.drop_index(batch_op.f('ix_emergency_access_grants_patient_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_access_grants_expires_at'))
        batch_op.drop_index(batch_op.f('ix_emergency_access_grants_clinic_id'))
        batch_op.drop_index('ix_emergency_access_expires_at')
        batch_op.drop_index('ix_emergency_access_clinic_patient_status')

    op.drop_table('emergency_access_grants')
    # ### end Alembic commands ###
