"""Make gateway transaction ID unique

Revision ID: c9552919543e
Revises: 25b67cf44379
Create Date: 2026-09-06 12:10:55.866171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9552919543e'
down_revision = '25b67cf44379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_auth_identity_provider_user'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_auth_identity_user_provider')
    )
    with op.batch_alter_table('user_auth_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_auth_identities_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_gateway_transaction_id'))
        batch_op.create_index(batch_op.f('ix_payments_gateway_transaction_id'), ['gateway_transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_gateway_transaction_id'))
        batch_op.create_index(batch_op.f('ix_payments_gateway_transaction_id'), ['gateway_transaction_id'], unique=False)

    with op.batch_alter_table('user_auth_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_auth_identities_user_id'))

    op.drop_table('user_auth_identities')
    # ### end Alembic commands ###
