"""notifications and messages

Revision ID: e9b8af6e78e1
Revises: 0e5862cc2239
Create Date: 2026-09-07 16:34:45.926965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b8af6e78e1'
down_revision = '0e5862cc2239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('DIRECT', 'SYSTEM', 'CLINICAL', 'APPOINTMENT', 'LAB', 'PHARMACY', 'BILLING', 'GENERAL', name='messagetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ARCHIVED', name='messagestatus'), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'HIGH', 'URGENT', name='messagepriority'), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_parent_message_id'), ['parent_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_read_at'), ['read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('GENERAL', 'APPOINTMENT', 'CONSULTATION', 'LAB', 'PHARMACY', 'PRESCRIPTION', 'INVENTORY', 'BILLING', 'WARD', 'AMBULANCE', 'HIE', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'PUSH', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_delivered_at'), ['delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_failed_at'), ['failed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_read_at'), ['read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_sent_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_reference_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_reference_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_priority'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_failed_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_delivered_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_channel'))

    op.drop_table('notifications')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_status'))
        batch_op.drop_index(batch_op.f('ix_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_messages_read_at'))
        batch_op.drop_index(batch_op.f('ix_messages_priority'))
        batch_op.drop_index(batch_op.f('ix_messages_parent_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_messages_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_clinic_id'))

    op.drop_table('messages')
    # ### end Alembic commands ###
