"""updated asset control models

Revision ID: 2540f664a077
Revises: fd4fb0c80471
Create Date: 2026-09-18 16:32:14.876587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "2540f664a077"
down_revision = "fd4fb0c80471"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    asset_status_enum = postgresql.ENUM(
        "ACTIVE",
        "ASSIGNED",
        "IN_STORAGE",
        "UNDER_MAINTENANCE",
        "OUT_OF_SERVICE",
        "LOST",
        "RETIRED",
        "DISPOSED",
        name="asset_status",
        create_type=False,
    )

    asset_condition_enum = postgresql.ENUM(
        "EXCELLENT",
        "GOOD",
        "FAIR",
        "POOR",
        "DAMAGED",
        "NON_FUNCTIONAL",
        name="asset_condition",
        create_type=False,
    )

    maintenance_status_enum = postgresql.ENUM(
        "NOT_REQUIRED",
        "SCHEDULED",
        "DUE",
        "IN_PROGRESS",
        "COMPLETED",
        "OVERDUE",
        name="maintenance_status",
        create_type=False,
    )

    op.create_table(
        "asset_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("clinic_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "returned_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "assigned_by_user_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "returned_by_user_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "returned_at IS NULL OR returned_at >= assigned_at",
            name="ck_asset_assignments_returned_after_assigned",
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["returned_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table(
        "asset_assignments",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_asset_assignments_asset_id"),
            ["asset_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_assignments_assigned_at"),
            ["assigned_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_assignments_assigned_by_user_id"),
            ["assigned_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_asset_assignments_clinic_asset_assigned",
            ["clinic_id", "asset_id", "assigned_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_assignments_clinic_id"),
            ["clinic_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_asset_assignments_clinic_staff_assigned",
            ["clinic_id", "staff_id", "assigned_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_assignments_returned_at"),
            ["returned_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_assignments_returned_by_user_id"),
            ["returned_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_assignments_staff_id"),
            ["staff_id"],
            unique=False,
        )

    op.create_table(
        "asset_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("clinic_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "CREATED",
                "UPDATED",
                "ASSIGNED",
                "UNASSIGNED",
                "LOCATION_CHANGED",
                "STATUS_CHANGED",
                "CONDITION_CHANGED",
                "MAINTENANCE_STARTED",
                "MAINTENANCE_COMPLETED",
                "MAINTENANCE_CANCELLED",
                "RETIRED",
                "DISPOSED",
                name="asset_history_event_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "previous_status",
            asset_status_enum,
            nullable=True,
        ),
        sa.Column(
            "new_status",
            asset_status_enum,
            nullable=True,
        ),
        sa.Column(
            "previous_condition",
            asset_condition_enum,
            nullable=True,
        ),
        sa.Column(
            "new_condition",
            asset_condition_enum,
            nullable=True,
        ),
        sa.Column(
            "previous_assigned_to_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "new_assigned_to_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "previous_location",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "new_location",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "actor_user_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "event_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "event_metadata",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["new_assigned_to_id"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_assigned_to_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table(
        "asset_history",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_asset_history_actor_user_id"),
            ["actor_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_history_asset_id"),
            ["asset_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_asset_history_clinic_asset_event",
            ["clinic_id", "asset_id", "event_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_history_clinic_id"),
            ["clinic_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_history_event_at"),
            ["event_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_history_event_type"),
            ["event_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_history_new_assigned_to_id"),
            ["new_assigned_to_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_history_previous_assigned_to_id"),
            ["previous_assigned_to_id"],
            unique=False,
        )

    op.create_table(
        "asset_maintenance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("clinic_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            maintenance_status_enum,
            nullable=False,
        ),
        sa.Column(
            "scheduled_date",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "performed_by_user_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "cost",
            sa.Numeric(precision=14, scale=2),
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR "
            "started_at IS NULL OR "
            "completed_at >= started_at",
            name="ck_asset_maintenance_completed_after_started",
        ),
        sa.CheckConstraint(
            "cost IS NULL OR cost >= 0",
            name="ck_asset_maintenance_cost_non_negative",
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table(
        "asset_maintenance",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_asset_maintenance_asset_id"),
            ["asset_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_asset_maintenance_clinic_asset_scheduled",
            ["clinic_id", "asset_id", "scheduled_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_maintenance_clinic_id"),
            ["clinic_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_maintenance_completed_at"),
            ["completed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_maintenance_performed_by_user_id"),
            ["performed_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_maintenance_scheduled_date"),
            ["scheduled_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_maintenance_started_at"),
            ["started_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_asset_maintenance_status"),
            ["status"],
            unique=False,
        )

    with op.batch_alter_table(
        "chat_conversations",
        schema=None,
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "direct_key",
                sa.String(length=64),
                nullable=True,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_chat_conversations_direct_key"),
            ["direct_key"],
            unique=False,
        )
        batch_op.create_index(
            "uq_chat_conversations_active_direct_key",
            ["clinic_id", "direct_key"],
            unique=True,
            postgresql_where=sa.text(
                "conversation_type = 'direct' "
                "AND status = 'active' "
                "AND direct_key IS NOT NULL"
            ),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table(
        "chat_conversations",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            "uq_chat_conversations_active_direct_key",
            postgresql_where=sa.text(
                "conversation_type = 'direct' "
                "AND status = 'active' "
                "AND direct_key IS NOT NULL"
            ),
        )
        batch_op.drop_index(
            batch_op.f("ix_chat_conversations_direct_key")
        )
        batch_op.drop_column("direct_key")

    with op.batch_alter_table(
        "asset_maintenance",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_asset_maintenance_status")
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_maintenance_started_at")
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_maintenance_scheduled_date")
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_asset_maintenance_performed_by_user_id"
            )
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_maintenance_completed_at")
        )
        batch_op.drop_index(
            "ix_asset_maintenance_clinic_asset_scheduled"
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_maintenance_clinic_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_maintenance_asset_id")
        )

    op.drop_table("asset_maintenance")

    with op.batch_alter_table(
        "asset_history",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_asset_history_previous_assigned_to_id"
            )
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_history_new_assigned_to_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_history_event_type")
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_history_event_at")
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_history_clinic_id")
        )
        batch_op.drop_index(
            "ix_asset_history_clinic_asset_event"
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_history_asset_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_history_actor_user_id")
        )

    op.drop_table("asset_history")

    with op.batch_alter_table(
        "asset_assignments",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_asset_assignments_staff_id")
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_asset_assignments_returned_by_user_id"
            )
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_assignments_returned_at")
        )
        batch_op.drop_index(
            "ix_asset_assignments_clinic_staff_assigned"
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_assignments_clinic_id")
        )
        batch_op.drop_index(
            "ix_asset_assignments_clinic_asset_assigned"
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_asset_assignments_assigned_by_user_id"
            )
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_assignments_assigned_at")
        )
        batch_op.drop_index(
            batch_op.f("ix_asset_assignments_asset_id")
        )

    op.drop_table("asset_assignments")

    # ### end Alembic commands ###