"""all files connected

Revision ID: 2dadf8187f40
Revises: 26c78d1f0921
Create Date: 2026-09-03 13:46:32.967782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2dadf8187f40'
down_revision = '26c78d1f0921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('ambulance_trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('ambulance_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('dispense_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('drug_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('reorder_level',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('reorder_level',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('inventory_suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('patient_family_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('patient_insurances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('ward_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward_transfers', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('DOCTOR', 'NURSE', 'PHARMACIST', 'LAB_TECHNICIAN', 'RECEPTIONIST', 'ADMIN', 'ACCOUNTANT', 'OTHER', name='staffrole'), autoincrement=False, nullable=False))

    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('patient_insurances', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('patient_family_members', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('inventory_suppliers', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('reorder_level',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('drug_batches', schema=None) as batch_op:
        batch_op.alter_column('reorder_level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('dispense_records', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('ambulance_vehicles', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('ambulance_trips', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
