"""pharmarcy model updated

Revision ID: 3c759eb0d381
Revises: 05030326d223
Create Date: 2026-09-03 08:54:06.495487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c759eb0d381'
down_revision = '05030326d223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispense_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'prescription_items', ['prescription_item_id'], ['id'])

    with op.batch_alter_table('drug_batches', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_drug_batch_number', ['drug_id', 'batch_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug_batches', schema=None) as batch_op:
        batch_op.drop_constraint('uq_drug_batch_number', type_='unique')

    with op.batch_alter_table('dispense_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prescription_item_id')

    # ### end Alembic commands ###
