"""align schema with current models

Revision ID: 6b565bc6d8b8
Revises: 4d205e66d288
Create Date: 2026-10-05 16:46:52.931410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b565bc6d8b8'
down_revision = '4d205e66d288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ambulance_trips', schema=None) as batch_op:
        batch_op.create_index('ix_ambulance_trips_clinic_requested', ['clinic_id', 'requested_at', 'id'], unique=False)
        batch_op.create_index('ix_ambulance_trips_clinic_status_requested', ['clinic_id', 'status', 'requested_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulance_trips_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulance_trips_status'), ['status'], unique=False)

    with op.batch_alter_table('ambulance_vehicles', schema=None) as batch_op:
        batch_op.create_index('ix_ambulance_vehicles_clinic_plate', ['clinic_id', 'plate_number'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['api_token'])

    with op.batch_alter_table('dispense_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispense_items_dispense_record_id'))
        batch_op.drop_index(batch_op.f('ix_dispense_items_prescription_item_id'))
        batch_op.drop_index(batch_op.f('ix_dispense_items_batch_id'))
        batch_op.create_index('ix_dispense_items_batch_id', ['batch_id', 'id'], unique=False)
        batch_op.create_index('ix_dispense_items_prescription_item', ['prescription_item_id', 'id'], unique=False)
        batch_op.create_index('ix_dispense_items_record_id', ['dispense_record_id', 'id'], unique=False)

    with op.batch_alter_table('dispense_records', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('dispensed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_dispense_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispense_records_dispensed_at'), ['dispensed_at'], unique=False)
        batch_op.create_index('ix_dispense_records_prescription_created', ['prescription_id', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_dispense_records_status_created', ['status', 'created_at', 'id'], unique=False)

    with op.batch_alter_table('drug_batches', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('received_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_drug_batches_clinic_drug_expiry', ['clinic_id', 'drug_id', 'expiry_date', 'id'], unique=False)
        batch_op.create_index('ix_drug_batches_clinic_expiry_stock', ['clinic_id', 'expiry_date', 'quantity_on_hand', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drug_batches_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_drug_interaction_pair', ['drug_a_id', 'drug_b_id'])

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_drugs_clinic_active_name', ['clinic_id', 'is_active', 'name', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drugs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('hie_integrations', schema=None) as batch_op:
        batch_op.create_index('ix_hie_integrations_clinic_status_provider', ['clinic_id', 'status', 'provider'], unique=False)
        batch_op.create_unique_constraint('uq_hie_integrations_id_clinic', ['id', 'clinic_id'])

    with op.batch_alter_table('hie_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hie_submissions_integration_id'))
        batch_op.create_index('ix_hie_submissions_clinic_created_id', ['clinic_id', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_hie_submissions_clinic_patient_created', ['clinic_id', 'patient_id', 'created_at'], unique=False)
        batch_op.create_index('ix_hie_submissions_clinic_status_created', ['clinic_id', 'status', 'created_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('hie_submissions_integration_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_hie_submissions_integration_clinic', 'hie_integrations', ['integration_id', 'clinic_id'], ['id', 'clinic_id'])

    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.alter_column('received_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_inventory_batches_item_active_expiry', ['item_id', 'is_active', 'expiry_date'], unique=False)
        batch_op.create_unique_constraint('uq_inventory_batch_item_batch_number', ['item_id', 'batch_number'])

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_inventory_items_clinic_active_category', ['clinic_id', 'is_active', 'category'], unique=False)
        batch_op.create_index('ix_inventory_items_clinic_name', ['clinic_id', 'name'], unique=False)
        batch_op.create_unique_constraint('uq_inventory_item_clinic_name_category', ['clinic_id', 'name', 'category'])

    with op.batch_alter_table('inventory_suppliers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_inventory_suppliers_clinic_active_name', ['clinic_id', 'is_active', 'name'], unique=False)

    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.alter_column('requested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('cancelled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_inventory_transfers_destination_status_created', ['destination_clinic_id', 'status', 'created_at'], unique=False)
        batch_op.create_index('ix_inventory_transfers_source_status_created', ['source_clinic_id', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_items_invoice_id_id', ['invoice_id', 'id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_invoices_clinic_patient_created', ['clinic_id', 'patient_id', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_invoices_clinic_status_due', ['clinic_id', 'status', 'due_date', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('lab_order_items', schema=None) as batch_op:
        batch_op.alter_column('resulted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index('ix_lab_order_items_order_resulted_at', ['order_id', 'resulted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_order_items_resulted_at'), ['resulted_at'], unique=False)
        batch_op.create_index('ix_lab_order_items_test_flag', ['test_id', 'flag'], unique=False)

    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.alter_column('sample_collected_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('processed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index('ix_lab_orders_clinic_ordered_by_created', ['clinic_id', 'ordered_by_id', 'created_at'], unique=False)
        batch_op.create_index('ix_lab_orders_clinic_patient_created', ['clinic_id', 'patient_id', 'created_at'], unique=False)
        batch_op.create_index('ix_lab_orders_clinic_status_created', ['clinic_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_lab_orders_patient_created', ['patient_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_processed_at'), ['processed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_sample_collected_at'), ['sample_collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_verified_at'), ['verified_at'], unique=False)

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_lab_tests_clinic_active_name', ['clinic_id', 'is_active', 'name'], unique=False)
        batch_op.create_index('ix_lab_tests_clinic_sample_type', ['clinic_id', 'sample_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_tests_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('patient_family_members', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_patient_family_members_is_emergency_contact'), ['is_emergency_contact'], unique=False)
        batch_op.create_index('ix_patient_family_members_patient_emergency_name', ['patient_id', 'is_emergency_contact', 'full_name', 'id'], unique=False)

    with op.batch_alter_table('patient_insurances', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_patient_insurances_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_patient_insurances_patient_priority', ['patient_id', 'is_primary', 'is_active', 'created_at', 'id'], unique=False)

    with op.batch_alter_table('patient_vitals', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_patient_vitals_patient_consultation', ['patient_id', 'consultation_id', 'id'], unique=False)
        batch_op.create_index('ix_patient_vitals_patient_recorded', ['patient_id', 'recorded_at', 'id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('emirates_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_patients_clinic_active_name', ['clinic_id', 'is_active', 'last_name', 'first_name', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('paid_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_payments_invoice_status_created', ['invoice_id', 'status', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.alter_column('dosage',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('instructions',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.create_index('ix_prescription_items_prescription_drug', ['prescription_id', 'drug_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('prescription_items_prescription_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'prescriptions', ['prescription_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('issued_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_prescriptions_clinic_patient_issued', ['clinic_id', 'patient_id', 'issued_at', 'id'], unique=False)
        batch_op.create_index('ix_prescriptions_clinic_patient_status_issued', ['clinic_id', 'patient_id', 'status', 'issued_at', 'id'], unique=False)
        batch_op.create_index('ix_prescriptions_clinic_status_issued', ['clinic_id', 'status', 'issued_at', 'id'], unique=False)
        batch_op.create_index('ix_prescriptions_expiration_status', ['status', 'expires_at'], unique=False)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index('ix_stock_movements_batch_created_id', ['batch_id', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_stock_movements_item_created_id', ['item_id', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_stock_movements_performed_by_created', ['performed_by_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movements_performed_by_created')
        batch_op.drop_index('ix_stock_movements_item_created_id')
        batch_op.drop_index('ix_stock_movements_batch_created_id')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_prescriptions_expiration_status')
        batch_op.drop_index('ix_prescriptions_clinic_status_issued')
        batch_op.drop_index('ix_prescriptions_clinic_patient_status_issued')
        batch_op.drop_index('ix_prescriptions_clinic_patient_issued')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('issued_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prescription_items_prescription_id_fkey'), 'prescriptions', ['prescription_id'], ['id'])
        batch_op.drop_index('ix_prescription_items_prescription_drug')
        batch_op.alter_column('instructions',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('frequency',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('dosage',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_updated_at'))
        batch_op.drop_index('ix_payments_invoice_status_created')
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.alter_column('paid_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_created_at'))
        batch_op.drop_index('ix_patients_clinic_active_name')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('emirates_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('patient_vitals', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_vitals_patient_recorded')
        batch_op.drop_index('ix_patient_vitals_patient_consultation')
        batch_op.alter_column('recorded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('patient_insurances', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_insurances_patient_priority')
        batch_op.drop_index(batch_op.f('ix_patient_insurances_created_at'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('patient_family_members', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_family_members_patient_emergency_name')
        batch_op.drop_index(batch_op.f('ix_patient_family_members_is_emergency_contact'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_tests_created_at'))
        batch_op.drop_index('ix_lab_tests_clinic_sample_type')
        batch_op.drop_index('ix_lab_tests_clinic_active_name')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_orders_verified_at'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_sample_collected_at'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_processed_at'))
        batch_op.drop_index('ix_lab_orders_patient_created')
        batch_op.drop_index(batch_op.f('ix_lab_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_completed_at'))
        batch_op.drop_index('ix_lab_orders_clinic_status_created')
        batch_op.drop_index('ix_lab_orders_clinic_patient_created')
        batch_op.drop_index('ix_lab_orders_clinic_ordered_by_created')
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('processed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('sample_collected_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('lab_order_items', schema=None) as batch_op:
        batch_op.drop_index('ix_lab_order_items_test_flag')
        batch_op.drop_index(batch_op.f('ix_lab_order_items_resulted_at'))
        batch_op.drop_index('ix_lab_order_items_order_resulted_at')
        batch_op.alter_column('resulted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_updated_at'))
        batch_op.drop_index(batch_op.f('ix_invoices_due_date'))
        batch_op.drop_index(batch_op.f('ix_invoices_created_at'))
        batch_op.drop_index('ix_invoices_clinic_status_due')
        batch_op.drop_index('ix_invoices_clinic_patient_created')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index('ix_invoice_items_invoice_id_id')

    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_transfers_source_status_created')
        batch_op.drop_index('ix_inventory_transfers_destination_status_created')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('cancelled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('requested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('inventory_suppliers', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_suppliers_clinic_active_name')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_inventory_item_clinic_name_category', type_='unique')
        batch_op.drop_index('ix_inventory_items_clinic_name')
        batch_op.drop_index('ix_inventory_items_clinic_active_category')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.drop_constraint('uq_inventory_batch_item_batch_number', type_='unique')
        batch_op.drop_index('ix_inventory_batches_item_active_expiry')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('received_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('hie_submissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_hie_submissions_integration_clinic', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hie_submissions_integration_id_fkey'), 'hie_integrations', ['integration_id'], ['id'])
        batch_op.drop_index('ix_hie_submissions_clinic_status_created')
        batch_op.drop_index('ix_hie_submissions_clinic_patient_created')
        batch_op.drop_index('ix_hie_submissions_clinic_created_id')
        batch_op.create_index(batch_op.f('ix_hie_submissions_integration_id'), ['integration_id'], unique=False)

    with op.batch_alter_table('hie_integrations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_hie_integrations_id_clinic', type_='unique')
        batch_op.drop_index('ix_hie_integrations_clinic_status_provider')

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drugs_created_at'))
        batch_op.drop_index('ix_drugs_clinic_active_name')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_drug_interaction_pair', type_='unique')

    with op.batch_alter_table('drug_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drug_batches_created_at'))
        batch_op.drop_index('ix_drug_batches_clinic_expiry_stock')
        batch_op.drop_index('ix_drug_batches_clinic_drug_expiry')
        batch_op.alter_column('received_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('dispense_records', schema=None) as batch_op:
        batch_op.drop_index('ix_dispense_records_status_created')
        batch_op.drop_index('ix_dispense_records_prescription_created')
        batch_op.drop_index(batch_op.f('ix_dispense_records_dispensed_at'))
        batch_op.drop_index(batch_op.f('ix_dispense_records_created_at'))
        batch_op.alter_column('dispensed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('dispense_items', schema=None) as batch_op:
        batch_op.drop_index('ix_dispense_items_record_id')
        batch_op.drop_index('ix_dispense_items_prescription_item')
        batch_op.drop_index('ix_dispense_items_batch_id')
        batch_op.create_index(batch_op.f('ix_dispense_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispense_items_prescription_item_id'), ['prescription_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispense_items_dispense_record_id'), ['dispense_record_id'], unique=False)

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_ip_address'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('ambulance_vehicles', schema=None) as batch_op:
        batch_op.drop_index('ix_ambulance_vehicles_clinic_plate')

    with op.batch_alter_table('ambulance_trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambulance_trips_status'))
        batch_op.drop_index(batch_op.f('ix_ambulance_trips_requested_at'))
        batch_op.drop_index('ix_ambulance_trips_clinic_status_requested')
        batch_op.drop_index('ix_ambulance_trips_clinic_requested')

    # ### end Alembic commands ###
