"""initial migrate

Revision ID: 791b6e602bbe
Revises: 08e748d93daa
Create Date: 2026-08-27 09:22:45.484999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791b6e602bbe'
down_revision = '08e748d93daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_credits', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('api_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ai_requests_this_month', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_column('ai_requests_this_month')
        batch_op.drop_column('api_token')
        batch_op.drop_column('ai_credits')

    # ### end Alembic commands ###
