"""Add clinic settings

Revision ID: 91b56a427abc
Revises: 
Create Date: 2026-09-10 17:42:25.798597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91b56a427abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.create_index('ix_admissions_bed_status_admitted', ['bed_id', 'status', 'admitted_at'], unique=False)
        batch_op.create_index('ix_admissions_patient_status_admitted', ['patient_id', 'status', 'admitted_at'], unique=False)

    with op.batch_alter_table('bed_reservations', schema=None) as batch_op:
        batch_op.create_index('ix_bed_reservations_bed_status_expiry', ['bed_id', 'status', 'expires_at'], unique=False)
        batch_op.create_index('ix_bed_reservations_patient_status_reserved', ['patient_id', 'status', 'reserved_at'], unique=False)

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.create_index('ix_beds_ward_status_number', ['ward_id', 'status', 'bed_number'], unique=False)

    with op.batch_alter_table('excuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excuses_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_excuses_leave_request_created', ['leave_request_id', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_excuses_staff_created', ['staff_id', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_excuses_staff_status_created', ['staff_id', 'status', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_excuses_status_created', ['status', 'created_at', 'id'], unique=False)

    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index('ix_leave_requests_staff_status_period', ['staff_id', 'status', 'start_date', 'end_date', 'id'], unique=False)
        batch_op.create_index('ix_leave_requests_status_period', ['status', 'start_date', 'end_date', 'id'], unique=False)

    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_records_paid_at'), ['paid_at'], unique=False)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_issued_at'), ['issued_at'], unique=False)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index('ix_staff_clinic_specialty', ['clinic_id', 'specialty'], unique=False)
        batch_op.create_index('ix_staff_clinic_status_name', ['clinic_id', 'status', 'last_name', 'first_name', 'id'], unique=False)

    with op.batch_alter_table('ward_transfers', schema=None) as batch_op:
        batch_op.create_index('ix_ward_transfers_admission_created', ['admission_id', 'created_at'], unique=False)
        batch_op.create_index('ix_ward_transfers_to_bed_created', ['to_bed_id', 'created_at'], unique=False)

    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.create_index('ix_wards_clinic_type_name', ['clinic_id', 'ward_type', 'name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.drop_index('ix_wards_clinic_type_name')

    with op.batch_alter_table('ward_transfers', schema=None) as batch_op:
        batch_op.drop_index('ix_ward_transfers_to_bed_created')
        batch_op.drop_index('ix_ward_transfers_admission_created')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_clinic_status_name')
        batch_op.drop_index('ix_staff_clinic_specialty')

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_issued_at'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_created_at'))

    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_records_paid_at'))
        batch_op.drop_index(batch_op.f('ix_payroll_records_created_at'))

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_leave_requests_status_period')
        batch_op.drop_index('ix_leave_requests_staff_status_period')
        batch_op.drop_index(batch_op.f('ix_leave_requests_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_created_at'))

    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('excuses', schema=None) as batch_op:
        batch_op.drop_index('ix_excuses_status_created')
        batch_op.drop_index('ix_excuses_staff_status_created')
        batch_op.drop_index('ix_excuses_staff_created')
        batch_op.drop_index('ix_excuses_leave_request_created')
        batch_op.drop_index(batch_op.f('ix_excuses_created_at'))

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.drop_index('ix_beds_ward_status_number')

    with op.batch_alter_table('bed_reservations', schema=None) as batch_op:
        batch_op.drop_index('ix_bed_reservations_patient_status_reserved')
        batch_op.drop_index('ix_bed_reservations_bed_status_expiry')

    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_index('ix_admissions_patient_status_admitted')
        batch_op.drop_index('ix_admissions_bed_status_admitted')

    # ### end Alembic commands ###
