"""initial migrate

Revision ID: 92e8335b8cef
Revises: 1e846644bab0
Create Date: 2026-09-04 17:48:49.824772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92e8335b8cef'
down_revision = '1e846644bab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispense_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispense_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispense_items_dispense_record_id'), ['dispense_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispense_items_prescription_item_id'), ['prescription_item_id'], unique=False)

    with op.batch_alter_table('dispense_records', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_dispense_records_dispensed_by_id'), ['dispensed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispense_records_prescription_id'), ['prescription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispense_records_status'), ['status'], unique=False)

    with op.batch_alter_table('drug_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_id', sa.Integer(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('received_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_drug_batch_number'), type_='unique')
        batch_op.create_index(batch_op.f('ix_drug_batches_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drug_batches_drug_id'), ['drug_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drug_batches_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_drug_batches_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_unique_constraint('uq_drug_batch_clinic_drug_number', ['clinic_id', 'drug_id', 'batch_number'])
        batch_op.create_foreign_key(None, 'clinics', ['clinic_id'], ['id'])

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.alter_column('is_controlled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('drugs_barcode_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_drugs_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_drugs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_drugs_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drugs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_drugs_rxnorm_code'), ['rxnorm_code'], unique=False)

    with op.batch_alter_table('lab_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_order_items_flag'), ['flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_order_items_test_id'), ['test_id'], unique=False)
        batch_op.create_unique_constraint('uq_lab_order_item_order_test', ['order_id', 'test_id'])

    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('lab_orders_qr_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_lab_orders_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_consultation_id'), ['consultation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_equipment_reference_id'), ['equipment_reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_ordered_by_id'), ['ordered_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_qr_code'), ['qr_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_lab_orders_status'), ['status'], unique=False)

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('lab_tests_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_lab_tests_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_tests_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_lab_tests_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_tests_loinc_code'), ['loinc_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_tests_sample_type'), ['sample_type'], unique=False)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_leave_type'), ['leave_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_reviewed_by_id'), ['reviewed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('patient_family_members', schema=None) as batch_op:
        batch_op.alter_column('is_emergency_contact',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_patient_family_members_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_family_members_related_patient_id'), ['related_patient_id'], unique=False)

    with op.batch_alter_table('patient_insurances', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_patient_insurances_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_insurances_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('patient_vitals', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_patient_vitals_consultation_id'), ['consultation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_vitals_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_vitals_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_vitals_recorded_by_id'), ['recorded_by_id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('blood_type',
               existing_type=postgresql.ENUM('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', 'UNKNOWN', name='bloodtype'),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('patients_emirates_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('patients_patient_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('patients_umrn_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_patients_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_emirates_id'), ['emirates_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_patient_number'), ['patient_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_umrn'), ['umrn'], unique=True)

    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.alter_column('base_salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('bonuses',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('deductions',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('net_pay',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_payroll_records_staff_id'), ['staff_id'], unique=False)
        batch_op.create_unique_constraint('uq_payroll_staff_period', ['staff_id', 'pay_period_start', 'pay_period_end'])

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('staff_user_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_staff_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_specialty'), ['specialty'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_user_id'))
        batch_op.drop_index(batch_op.f('ix_staff_status'))
        batch_op.drop_index(batch_op.f('ix_staff_specialty'))
        batch_op.drop_index(batch_op.f('ix_staff_clinic_id'))
        batch_op.create_unique_constraint(batch_op.f('staff_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payroll_staff_period', type_='unique')
        batch_op.drop_index(batch_op.f('ix_payroll_records_staff_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('net_pay',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('deductions',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('bonuses',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('base_salary',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_umrn'))
        batch_op.drop_index(batch_op.f('ix_patients_patient_number'))
        batch_op.drop_index(batch_op.f('ix_patients_is_active'))
        batch_op.drop_index(batch_op.f('ix_patients_emirates_id'))
        batch_op.drop_index(batch_op.f('ix_patients_clinic_id'))
        batch_op.create_unique_constraint(batch_op.f('patients_umrn_key'), ['umrn'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('patients_patient_number_key'), ['patient_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('patients_emirates_id_key'), ['emirates_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('blood_type',
               existing_type=postgresql.ENUM('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', 'UNKNOWN', name='bloodtype'),
               nullable=True)

    with op.batch_alter_table('patient_vitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_vitals_recorded_by_id'))
        batch_op.drop_index(batch_op.f('ix_patient_vitals_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_patient_vitals_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_vitals_consultation_id'))
        batch_op.alter_column('recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('patient_insurances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_insurances_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_insurances_is_active'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('patient_family_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_family_members_related_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_family_members_patient_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_emergency_contact',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_status'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_staff_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_reviewed_by_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_leave_type'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_tests_sample_type'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_loinc_code'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_is_active'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_code'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_clinic_id'))
        batch_op.create_unique_constraint(batch_op.f('lab_tests_code_key'), ['code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_orders_status'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_qr_code'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_patient_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_ordered_by_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_equipment_reference_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_consultation_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_clinic_id'))
        batch_op.create_unique_constraint(batch_op.f('lab_orders_qr_code_key'), ['qr_code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('lab_order_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lab_order_item_order_test', type_='unique')
        batch_op.drop_index(batch_op.f('ix_lab_order_items_test_id'))
        batch_op.drop_index(batch_op.f('ix_lab_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_lab_order_items_flag'))

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drugs_rxnorm_code'))
        batch_op.drop_index(batch_op.f('ix_drugs_is_active'))
        batch_op.drop_index(batch_op.f('ix_drugs_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_drugs_category'))
        batch_op.drop_index(batch_op.f('ix_drugs_barcode'))
        batch_op.create_unique_constraint(batch_op.f('drugs_barcode_key'), ['barcode'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_controlled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('drug_batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_drug_batch_clinic_drug_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_drug_batches_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_drug_batches_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_drug_batches_drug_id'))
        batch_op.drop_index(batch_op.f('ix_drug_batches_clinic_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_drug_batch_number'), ['drug_id', 'batch_number'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('received_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('clinic_id')

    with op.batch_alter_table('dispense_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispense_records_status'))
        batch_op.drop_index(batch_op.f('ix_dispense_records_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_dispense_records_dispensed_by_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('dispense_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispense_items_prescription_item_id'))
        batch_op.drop_index(batch_op.f('ix_dispense_items_dispense_record_id'))
        batch_op.drop_index(batch_op.f('ix_dispense_items_batch_id'))

    # ### end Alembic commands ###
