"""add integration config

Revision ID: 9ba0c17415c2
Revises: 91b56a427abc
Create Date: 2026-09-10 18:55:11.959860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba0c17415c2'
down_revision = '91b56a427abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('date_format', sa.String(length=30), nullable=False),
    sa.Column('time_format', sa.String(length=10), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('feature_flags', sa.JSON(), nullable=False),
    sa.Column('operational_preferences', sa.JSON(), nullable=False),
    sa.Column('security_preferences', sa.JSON(), nullable=False),
    sa.Column('system_preferences', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_clinic_settings_version_positive'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinic_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_settings_clinic_id'), ['clinic_id'], unique=True)

    op.create_table('integration_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('credentials_version', sa.Integer(), nullable=False),
    sa.Column('last_rotated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('credentials_version >= 1', name='ck_integration_config_credentials_version_positive'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'provider', name='uq_integration_config_clinic_provider')
    )
    with op.batch_alter_table('integration_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_configs_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_configs_provider'), ['provider'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_configs_provider'))
        batch_op.drop_index(batch_op.f('ix_integration_configs_clinic_id'))

    op.drop_table('integration_configs')
    with op.batch_alter_table('clinic_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_settings_clinic_id'))

    op.drop_table('clinic_settings')
    # ### end Alembic commands ###
