"""all database full done

Revision ID: cb2be4f1c2ed
Revises: 92e8335b8cef
Create Date: 2026-09-05 07:30:03.684998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb2be4f1c2ed'
down_revision = '92e8335b8cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hie_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DISABLED', name='hieintegrationstatus'), nullable=False),
    sa.Column('endpoint_url', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.String(length=100), nullable=True),
    sa.Column('facility_id', sa.String(length=100), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hie_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hie_integrations_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hie_integrations_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_hie_integrations_status'), ['status'], unique=False)

    op.create_table('hie_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.Enum('PATIENT_SUBMISSION', 'CLINICAL_DATA_SUBMISSION', 'CLINICAL_DOCUMENT_SUBMISSION', 'PATIENT_QUERY', 'CLINICAL_DATA_QUERY', name='hieoperation'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='hiesubmissionstatus'), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['hie_integrations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hie_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hie_submissions_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hie_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hie_submissions_external_reference'), ['external_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_hie_submissions_integration_id'), ['integration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hie_submissions_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_hie_submissions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hie_submissions_status'), ['status'], unique=False)

    op.create_table('inventory_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['inventory_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_batches_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('bed_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('reserved_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CANCELLED', 'EXPIRED', 'FULFILLED', name='reservationstatus'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reserved_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > reserved_at', name='ck_bed_reservations_valid_expiry'),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['reserved_by_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bed_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bed_reservations_bed_id'), ['bed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bed_reservations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bed_reservations_reserved_by_id'), ['reserved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bed_reservations_status'), ['status'], unique=False)

    op.create_table('inventory_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('source_clinic_id', sa.Integer(), nullable=False),
    sa.Column('destination_clinic_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED', name='inventorytransferstatus'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['destination_clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['source_clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transfers_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transfers_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transfers_destination_clinic_id'), ['destination_clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transfers_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transfers_requested_by_id'), ['requested_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transfers_source_clinic_id'), ['source_clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transfers_status'), ['status'], unique=False)

    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_admissions_reservation_id'), ['reservation_id'], unique=False)
        batch_op.create_foreign_key(None, 'bed_reservations', ['reservation_id'], ['id'])

    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_ai_logs_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_logs_feature_used'), ['feature_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_logs_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_generated_reports_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_reports_generated_by_id'), ['generated_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_reports_report_format'), ['report_format'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_reports_report_type'), ['report_type'], unique=False)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('inventory_items_barcode_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('inventory_items_sku_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_inventory_items_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_sku'), ['sku'], unique=True)
        batch_op.drop_constraint(batch_op.f('inventory_items_supplier_id_fkey'), type_='foreignkey')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('unit_cost')
        batch_op.drop_column('expiry_date')

    with op.batch_alter_table('inventory_suppliers', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_inventory_suppliers_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_suppliers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_suppliers_name'), ['name'], unique=False)

    # --- FIX: explicitly create the enum type BEFORE the batch_alter_table below.
    # Batch mode does not auto-CREATE TYPE the way op.create_table(...) does,
    # so we create it manually here and reference it with create_type=False
    # inside the add_column call to avoid a duplicate creation attempt.
    stockmovementdirection = postgresql.ENUM(
        'IN', 'OUT',
        name='stockmovementdirection'
    )
    stockmovementdirection.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column(
            'direction',
            postgresql.ENUM('IN', 'OUT', name='stockmovementdirection', create_type=False),
            nullable=False,
            server_default='IN'  # required: existing rows need a value for the new NOT NULL column
        ))
        batch_op.add_column(sa.Column('reference_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.Integer(), nullable=True))
        batch_op.alter_column('performed_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_performed_by_id'), ['performed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_reference_type'), ['reference_type'], unique=False)
        batch_op.create_foreign_key(None, 'inventory_batches', ['batch_id'], ['id'])

        # Optional: drop the server_default now that existing rows are backfilled,
        # so new inserts must specify direction explicitly going forward.
        # Comment this out if you want to keep 'IN' as a permanent default.
        batch_op.alter_column('direction', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stock_movements_reference_type'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_reference_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_performed_by_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_direction'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_at'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_batch_id'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('performed_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('reference_id')
        batch_op.drop_column('reference_type')
        batch_op.drop_column('direction')
        batch_op.drop_column('batch_id')

    # --- FIX: drop the enum type after the column that uses it is gone.
    postgresql.ENUM(name='stockmovementdirection').drop(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('inventory_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_inventory_suppliers_is_active'))
        batch_op.drop_index(batch_op.f('ix_inventory_suppliers_clinic_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unit_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('inventory_items_supplier_id_fkey'), 'inventory_suppliers', ['supplier_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_inventory_items_sku'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_name'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_is_active'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_category'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_barcode'))
        batch_op.create_unique_constraint(batch_op.f('inventory_items_sku_key'), ['sku'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('inventory_items_barcode_key'), ['barcode'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_report_format'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_generated_by_id'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_clinic_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ai_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_logs_patient_id'))
        batch_op.drop_index(batch_op.f('ix_ai_logs_feature_used'))
        batch_op.drop_index(batch_op.f('ix_ai_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_logs_clinic_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_admissions_reservation_id'))
        batch_op.drop_column('reservation_id')

    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transfers_status'))
        batch_op.drop_index(batch_op.f('ix_inventory_transfers_source_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transfers_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transfers_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transfers_destination_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transfers_batch_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transfers_approved_by_id'))

    op.drop_table('inventory_transfers')
    with op.batch_alter_table('bed_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bed_reservations_status'))
        batch_op.drop_index(batch_op.f('ix_bed_reservations_reserved_by_id'))
        batch_op.drop_index(batch_op.f('ix_bed_reservations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_bed_reservations_bed_id'))

    op.drop_table('bed_reservations')
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_batches_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_is_active'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_batch_number'))

    op.drop_table('inventory_batches')
    with op.batch_alter_table('hie_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hie_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_hie_submissions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_hie_submissions_operation'))
        batch_op.drop_index(batch_op.f('ix_hie_submissions_integration_id'))
        batch_op.drop_index(batch_op.f('ix_hie_submissions_external_reference'))
        batch_op.drop_index(batch_op.f('ix_hie_submissions_created_at'))
        batch_op.drop_index(batch_op.f('ix_hie_submissions_clinic_id'))

    op.drop_table('hie_submissions')
    with op.batch_alter_table('hie_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hie_integrations_status'))
        batch_op.drop_index(batch_op.f('ix_hie_integrations_provider'))
        batch_op.drop_index(batch_op.f('ix_hie_integrations_clinic_id'))

    op.drop_table('hie_integrations')
    # ### end Alembic commands ###