"""add feedback module

Revision ID: cc802fd6f67e
Revises: 70388a132ec2
Create Date: 2026-09-25 16:11:58.918199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc802fd6f67e'
down_revision = '70388a132ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.Enum('product_feedback', 'bug_report', 'feature_request', 'service_complaint', 'compliment', name='feedback_type_enum'), nullable=False),
    sa.Column('category', sa.Enum('usability', 'performance', 'accessibility', 'billing', 'appointment', 'pharmacy', 'laboratory', 'clinical_workflow', 'communication', 'security', 'other', name='feedback_category_enum'), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'triaged', 'in_progress', 'resolved', 'reopened', 'closed', 'rejected', name='feedback_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='feedback_priority_enum'), nullable=False),
    sa.Column('source', sa.Enum('web', 'mobile', 'api', 'system', name='feedback_source_enum'), nullable=False),
    sa.Column('target_module', sa.String(length=100), nullable=True),
    sa.Column('target_resource_type', sa.String(length=100), nullable=True),
    sa.Column('target_resource_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('\n            (\n                target_module IS NULL\n                AND target_resource_type IS NULL\n                AND target_resource_id IS NULL\n            )\n            OR\n            (\n                target_module IS NOT NULL\n                AND target_resource_type IS NOT NULL\n                AND target_resource_id IS NOT NULL\n                AND target_resource_id > 0\n            )\n            ', name='ck_feedback_target_fields_consistent'),
    sa.CheckConstraint('length(trim(message)) > 0', name='ck_feedback_message_not_blank'),
    sa.CheckConstraint('length(trim(subject)) > 0', name='ck_feedback_subject_not_blank'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index('ix_feedback_assigned_status_created_id', ['assigned_to_user_id', 'status', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_category'), ['category'], unique=False)
        batch_op.create_index('ix_feedback_clinic_category_created_id', ['clinic_id', 'category', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_feedback_clinic_created_id', ['clinic_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index('ix_feedback_clinic_priority_created_id', ['clinic_id', 'priority', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_feedback_clinic_status_created_id', ['clinic_id', 'status', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_feedback_clinic_type_created_id', ['clinic_id', 'feedback_type', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_closed_at'), ['closed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_feedback_type'), ['feedback_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)
        batch_op.create_index('ix_feedback_submitted_created_id', ['submitted_by_user_id', 'created_at', 'id'], unique=False)
        batch_op.create_index('ix_feedback_target_resource', ['target_module', 'target_resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_target_resource_id'), ['target_resource_id'], unique=False)

    op.create_table('feedback_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_comments', schema=None) as batch_op:
        batch_op.create_index('ix_feedback_comments_author_created_id', ['author_user_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_comments_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index('ix_feedback_comments_feedback_created_id', ['feedback_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_comments_feedback_id'), ['feedback_id'], unique=False)

    op.create_table('feedback_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.Enum('helpful', 'appreciated', 'not_helpful', name='feedback_reaction_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id', 'user_id', name='uq_feedback_reactions_feedback_user')
    )
    with op.batch_alter_table('feedback_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_reactions_feedback_id'), ['feedback_id'], unique=False)
        batch_op.create_index('ix_feedback_reactions_feedback_type', ['feedback_id', 'reaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_reactions_reaction_type'), ['reaction_type'], unique=False)
        batch_op.create_index('ix_feedback_reactions_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_reactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_reactions_user_id'))
        batch_op.drop_index('ix_feedback_reactions_user_created')
        batch_op.drop_index(batch_op.f('ix_feedback_reactions_reaction_type'))
        batch_op.drop_index('ix_feedback_reactions_feedback_type')
        batch_op.drop_index(batch_op.f('ix_feedback_reactions_feedback_id'))

    op.drop_table('feedback_reactions')
    with op.batch_alter_table('feedback_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_comments_feedback_id'))
        batch_op.drop_index('ix_feedback_comments_feedback_created_id')
        batch_op.drop_index(batch_op.f('ix_feedback_comments_author_user_id'))
        batch_op.drop_index('ix_feedback_comments_author_created_id')

    op.drop_table('feedback_comments')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_target_resource_id'))
        batch_op.drop_index('ix_feedback_target_resource')
        batch_op.drop_index('ix_feedback_submitted_created_id')
        batch_op.drop_index(batch_op.f('ix_feedback_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_status'))
        batch_op.drop_index(batch_op.f('ix_feedback_source'))
        batch_op.drop_index(batch_op.f('ix_feedback_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_feedback_priority'))
        batch_op.drop_index(batch_op.f('ix_feedback_feedback_type'))
        batch_op.drop_index(batch_op.f('ix_feedback_created_at'))
        batch_op.drop_index(batch_op.f('ix_feedback_closed_at'))
        batch_op.drop_index('ix_feedback_clinic_type_created_id')
        batch_op.drop_index('ix_feedback_clinic_status_created_id')
        batch_op.drop_index('ix_feedback_clinic_priority_created_id')
        batch_op.drop_index(batch_op.f('ix_feedback_clinic_id'))
        batch_op.drop_index('ix_feedback_clinic_created_id')
        batch_op.drop_index('ix_feedback_clinic_category_created_id')
        batch_op.drop_index(batch_op.f('ix_feedback_category'))
        batch_op.drop_index(batch_op.f('ix_feedback_assigned_to_user_id'))
        batch_op.drop_index('ix_feedback_assigned_status_created_id')

    op.drop_table('feedback')
    # ### end Alembic commands ###
