"""add user devices

Revision ID: dfc4ce4e901a
Revises: 9ba0c17415c2
Create Date: 2026-09-10 21:26:54.543341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc4ce4e901a'
down_revision = '9ba0c17415c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_token', sa.String(length=500), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_devices_device_token'), ['device_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_devices_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_devices_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_devices_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_devices_platform'))
        batch_op.drop_index(batch_op.f('ix_user_devices_is_active'))
        batch_op.drop_index(batch_op.f('ix_user_devices_device_token'))

    op.drop_table('user_devices')
    # ### end Alembic commands ###
