"""add reply support to chat messages

Revision ID: ef3b4d313dcb
Revises: 9ee239523799
Create Date: 2026-09-13 16:11:34.625254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3b4d313dcb'
down_revision = '9ee239523799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_message_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_messages_reply_to_message_id'), ['reply_to_message_id'], unique=False)
        batch_op.create_foreign_key(None, 'chat_messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_messages_reply_to_message_id'))
        batch_op.drop_column('reply_to_message_id')

    # ### end Alembic commands ###
